[package]
name = "a3_1_tex_quotes"
version = "0.1.0"
authors = ["fanghao.xin <fanghao_xin@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
